/**
 * Compatibility facade for the shared package surface.
 *
 * Concern implementations live in the focused modules below. Keep this file
 * deliberately boring: server, TUI, interop, and package consumers all import
 * this path, so its exports are the compatibility boundary.
 */

export type { ModelRef } from "@macarons/permission-rules"
export {
  formatModelRef,
  parseModelRef,
} from "@macarons/permission-rules"
export type {
  AuthorizationLevel,
  ClassifierRequest,
  PolicyAuthorizationLevel,
  PolicyRiskLevel,
  RiskLevel,
  Verdict,
} from "./shared/classifier-policy"
export {
  AUTHORIZATION_LEVELS,
  CLASSIFIER_SYSTEM_PROMPT,
  classifierUserPrompt,
  enforcedDecision,
  explicitCarveOut,
  matrixDecision,
  parseRuleArray,
  parseVerdict,
  RISK_LEVELS,
  selectTranscriptWindow,
  storeCarveOut,
  TOOL_CATALOG,
  TRANSCRIPT_MAX,
  TRANSCRIPT_MAX_ITEMS,
  TRUNCATE_SUFFIX,
  truncate,
  VERDICT_SCHEMA,
} from "./shared/classifier-policy"
export type {
  Blessing,
  EffectiveSettings,
  PluginConfigScan,
  PolicyFault,
  PolicySnapshot,
  ProcessingMode,
  ResolvedSettings,
  Settings,
  TrustedSettingsPaths,
  WorktreeConfigState,
  WorktreePolicy,
} from "./shared/config-policy"
export {
  blessFile,
  DEFAULT_MAX_CONCURRENT,
  DEFAULT_PROCESSING,
  DEFAULT_TIMEOUT_MS,
  DEFAULT_UNATTENDED_DENY_MS,
  escapesProject,
  evaluateWorktreePolicy,
  externalBoundaryDirectory,
  GLOBAL_SETTINGS_BASENAME,
  globalConfigCandidates,
  hostConfigRoot,
  isOwnPluginSpec,
  LEGACY_PROJECT_SETTINGS_BASENAME,
  legacyProjectSettingsFile,
  MAX_MAX_CONCURRENT,
  MAX_TIMEOUT_MS,
  MAX_UNATTENDED_DENY_MS,
  MIN_MAX_CONCURRENT,
  MIN_TIMEOUT_MS,
  MIN_UNATTENDED_DENY_MS,
  mergeSettings,
  ownPackageDir,
  PLUGIN_MODULE_ID,
  PLUGIN_PACKAGE_NAME,
  parseBlessing,
  parseSettings,
  patchGlobalEntryOptions,
  preSlugProjectSettingsFile,
  projectConfigDisabled,
  projectSettingsFile,
  readBlessing,
  readEffectiveSettings,
  readGlobalEntrySettings,
  readPolicySnapshot,
  readSettingsFile,
  reservedHostPaths,
  resolveGlobalCandidate,
  resolveReservedPath,
  resolveSettings,
  resolveTrustedSettingsPaths,
  scanPluginConfigFile,
  scanSideloadSources,
  scanWorktreeConfig,
  settingsLocalityPaths,
  sha256Hex,
  touchesHostConfig,
  touchesHostConfigResolved,
  touchesReservedPathResolved,
  UNATTENDED_DENY_LIMIT,
  unblessedSideloads,
  worktreeConfigCandidates,
  writeBlessing,
} from "./shared/config-policy"
export { requestInstanceID, respondInstanceRequest } from "./shared/instance"
export type {
  Activity,
  ActivityEntry,
  ActivityFile,
  ActivityState,
  ApprovalEntry,
  Approvals,
  ApprovalsJournal,
  Override,
  ServerStatus,
  SessionModelReadResult,
  SessionModelRecord,
} from "./shared/persisted-state"
export {
  ACTIVITY_MAX_ENTRIES,
  ACTIVITY_REASON_MAX,
  ACTIVITY_TTL_MS,
  APPROVALS_MAX_PATTERNS,
  activityFile,
  approvalsJournalFile,
  clearActivity,
  clearOverride,
  clearSessionModel,
  clearTrustedSessionModel,
  clearTrustedSessionModelIfUnchanged,
  emptyApprovals,
  listTrustedSessionModels,
  overrideFile,
  preSlugApprovalsJournalFile,
  pruneActivity,
  pruneApprovals,
  readActivity,
  readApprovalsJournal,
  readOverride,
  readSessionModel,
  readTrustedSessionModel,
  recordApproval,
  resolveTrustedSessionModelFile,
  SERVICE,
  STORAGE_SERVICE,
  sessionModelCapability,
  sessionModelDirectory,
  sessionModelFile,
  writeActivity,
  writeApprovalsJournal,
  writeOverride,
  writeSessionModel,
} from "./shared/persisted-state"
export type { StackPosition } from "./shared/state"
export {
  compareStackOrder,
  SESSION_ANCESTRY_HOP_LIMIT,
} from "./shared/state"
